import type {
  User,
  Category,
  Listing,
  Review,
  Order,
  Message,
  Conversation,
  DeliveryTask,
  DashboardStats,
  AdminStats,
} from "./types"

// --- USERS ---
export const users: User[] = [
  {
    id: "u1",
    name: "Akou Mensah",
    email: "akou@africamarket.bj",
    phone: "+229 97 12 34 56",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "seller",
    location: "Cotonou",
    bio: "Artisan menuisier avec plus de 15 ans d'experience. Specialise dans les meubles sur mesure en bois local.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.8,
    reviewCount: 127,
    listingsCount: 24,
    joinedAt: "2023-06-15",
    shopName: "Atelier Mensah",
    shopDescription: "Meubles artisanaux de qualite fabriques a la main",
    subscription: "basic",
  },
  {
    id: "u2",
    name: "Fati Adjovi",
    email: "fati@africamarket.bj",
    phone: "+229 96 45 67 89",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "seller",
    location: "Porto-Novo",
    bio: "Cuisiniere passionnee, je propose des plats traditionnels beninois et des services traiteur pour tous vos evenements.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.9,
    reviewCount: 203,
    listingsCount: 18,
    joinedAt: "2023-03-20",
    shopName: "Saveurs du Benin",
    shopDescription: "Cuisine traditionnelle beninoise authentique",
  },
  {
    id: "u3",
    name: "Koffi Dossou",
    email: "koffi@africamarket.bj",
    phone: "+229 95 78 90 12",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "seller",
    location: "Cotonou",
    bio: "Mecanicien auto certifie. Reparation, entretien et diagnostic de tous types de vehicules.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.6,
    reviewCount: 89,
    listingsCount: 12,
    joinedAt: "2023-09-10",
    shopName: "Garage Dossou",
    shopDescription: "Mecanique auto professionnelle",
  },
  {
    id: "u4",
    name: "Amina Bello",
    email: "amina@africamarket.bj",
    phone: "+229 94 56 78 90",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "seller",
    location: "Parakou",
    bio: "Couturiere et styliste. Creations de mode africaine moderne et traditionnelle.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.7,
    reviewCount: 156,
    listingsCount: 32,
    joinedAt: "2023-01-05",
    shopName: "Mode Amina",
    shopDescription: "Mode africaine contemporaine",
  },
  {
    id: "u5",
    name: "Jean-Baptiste Houessou",
    email: "jb@africamarket.bj",
    phone: "+229 91 23 45 67",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "buyer",
    location: "Cotonou",
    bio: "Amateur de produits artisanaux locaux.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.5,
    reviewCount: 34,
    listingsCount: 0,
    joinedAt: "2024-02-14",
  },
  {
    id: "u6",
    name: "Chantal Agossa",
    email: "chantal@africamarket.bj",
    phone: "+229 93 67 89 01",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "seller",
    location: "Abomey-Calavi",
    bio: "Specialiste en soins de beaute et coiffure. Produits naturels et bio.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.8,
    reviewCount: 178,
    listingsCount: 15,
    joinedAt: "2023-07-22",
    shopName: "Beaute Naturelle",
    shopDescription: "Soins de beaute naturels et coiffure",
  },
  {
    id: "u7",
    name: "Moussa Toure",
    email: "moussa@africamarket.bj",
    phone: "+229 92 34 56 78",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "seller",
    location: "Cotonou",
    bio: "Technicien en electronique et informatique. Reparation smartphones, ordinateurs et installation reseaux.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.5,
    reviewCount: 95,
    listingsCount: 20,
    joinedAt: "2023-11-01",
    shopName: "Tech Solutions BJ",
    shopDescription: "Reparation et services informatiques",
  },
  {
    id: "u8",
    name: "Admin AfricaMarket",
    email: "admin@africamarket.bj",
    phone: "+229 90 00 00 01",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "admin",
    location: "Cotonou",
    bio: "Administrateur de la plateforme AfricaMarket.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 5.0,
    reviewCount: 0,
    listingsCount: 0,
    joinedAt: "2023-01-01",
  },
  {
    id: "u9",
    name: "Serge Adandedjan",
    email: "serge@africamarket.bj",
    phone: "+229 96 11 22 33",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "delivery",
    location: "Cotonou",
    bio: "Livreur rapide et fiable. Je couvre Cotonou et ses environs.",
    isVerified: true,
    verificationStatus: "verified",
    rating: 4.7,
    reviewCount: 67,
    listingsCount: 0,
    joinedAt: "2024-01-15",
  },
  {
    id: "u10",
    name: "Grace Hounsa",
    email: "grace@africamarket.bj",
    phone: "+229 97 88 99 00",
    avatar: "/placeholder.svg?height=80&width=80",
    role: "buyer",
    location: "Porto-Novo",
    bio: "Passionnee de decoration interieure et d'artisanat local.",
    isVerified: false,
    verificationStatus: "none",
    rating: 4.2,
    reviewCount: 12,
    listingsCount: 0,
    joinedAt: "2024-06-01",
  },
]

// --- CATEGORIES ---
export const categories: Category[] = [
  { id: "cat1", name: "Mechanics", nameFr: "Mecanique", icon: "Wrench", slug: "mecanique", count: 245 },
  { id: "cat2", name: "Carpentry", nameFr: "Menuiserie", icon: "Hammer", slug: "menuiserie", count: 189 },
  { id: "cat3", name: "Restaurant", nameFr: "Restauration", icon: "UtensilsCrossed", slug: "restauration", count: 312 },
  { id: "cat4", name: "Electronics", nameFr: "Electronique", icon: "Smartphone", slug: "electronique", count: 278 },
  { id: "cat5", name: "Fashion", nameFr: "Mode & Vetements", icon: "Shirt", slug: "mode", count: 456 },
  { id: "cat6", name: "Beauty", nameFr: "Beaute & Bien-etre", icon: "Sparkles", slug: "beaute", count: 198 },
  { id: "cat7", name: "Home", nameFr: "Maison & Deco", icon: "Home", slug: "maison", count: 167 },
  { id: "cat8", name: "Agriculture", nameFr: "Agriculture", icon: "Leaf", slug: "agriculture", count: 134 },
  { id: "cat9", name: "Education", nameFr: "Education & Formation", icon: "GraduationCap", slug: "education", count: 89 },
  { id: "cat10", name: "Transport", nameFr: "Transport", icon: "Car", slug: "transport", count: 76 },
  { id: "cat11", name: "Health", nameFr: "Sante", icon: "Heart", slug: "sante", count: 112 },
  { id: "cat12", name: "Construction", nameFr: "Construction & BTP", icon: "Building2", slug: "construction", count: 203 },
]

// --- LISTINGS ---
export const listings: Listing[] = [
  {
    id: "l1",
    title: "Table a manger en bois massif 6 places",
    description: "Magnifique table a manger artisanale en bois d'iroko massif, fabriquee a la main. Dimensions: 180cm x 90cm x 75cm. Finition huilee naturelle. Livraison possible sur Cotonou.",
    type: "product",
    price: 185000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Menuiserie",
    categoryId: "cat2",
    seller: users[0],
    location: "Cotonou",
    quartier: "Akpakpa",
    rating: 4.9,
    reviewCount: 23,
    views: 1247,
    isPromoted: true,
    isFavorited: false,
    status: "active",
    createdAt: "2025-01-15",
    updatedAt: "2025-02-01",
    tags: ["bois", "artisanal", "iroko", "table"],
    deliveryAvailable: true,
    condition: "new",
  },
  {
    id: "l2",
    title: "Service traiteur - Buffet traditionnel beninois",
    description: "Service traiteur complet pour vos evenements. Menu traditionnel beninois incluant: pate rouge, sauce d'arachide, poisson braise, alloco, igname pilée. A partir de 50 personnes.",
    type: "service",
    price: 3500,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Restauration",
    categoryId: "cat3",
    seller: users[1],
    location: "Porto-Novo",
    quartier: "Ouando",
    rating: 4.9,
    reviewCount: 67,
    views: 2340,
    isPromoted: true,
    isFavorited: true,
    status: "active",
    createdAt: "2025-01-20",
    updatedAt: "2025-02-10",
    tags: ["traiteur", "cuisine", "evenement", "traditionnel"],
    deliveryAvailable: true,
    availability: "Sur reservation - 48h a l'avance",
  },
  {
    id: "l3",
    title: "Diagnostic et reparation auto toutes marques",
    description: "Service de diagnostic electronique et reparation mecanique pour tous types de vehicules. Equipement professionnel. Devis gratuit. Garantie sur les reparations.",
    type: "service",
    price: 15000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Mecanique",
    categoryId: "cat1",
    seller: users[2],
    location: "Cotonou",
    quartier: "Godomey",
    rating: 4.6,
    reviewCount: 45,
    views: 890,
    isPromoted: false,
    isFavorited: false,
    status: "active",
    createdAt: "2025-01-10",
    updatedAt: "2025-01-28",
    tags: ["mecanique", "auto", "diagnostic", "reparation"],
    deliveryAvailable: false,
    availability: "Lundi - Samedi, 8h - 18h",
  },
  {
    id: "l4",
    title: "Robe Ankara moderne - Collection 2025",
    description: "Robe elegante en tissu Ankara (wax hollandais). Coupe moderne, taille ajustee. Disponible en tailles S, M, L, XL. Confection sur mesure possible. Delai: 5 jours ouvrables.",
    type: "product",
    price: 25000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Mode & Vetements",
    categoryId: "cat5",
    seller: users[3],
    location: "Parakou",
    rating: 4.8,
    reviewCount: 89,
    views: 3456,
    isPromoted: true,
    isFavorited: true,
    status: "active",
    createdAt: "2025-02-01",
    updatedAt: "2025-02-12",
    tags: ["ankara", "mode", "robe", "wax", "femme"],
    deliveryAvailable: true,
    condition: "new",
  },
  {
    id: "l5",
    title: "Soin capillaire naturel complet",
    description: "Forfait soin capillaire comprenant: diagnostic, shampooing bio, masque hydratant, coupe et coiffure. Produits 100% naturels et locaux. Duree: environ 2h.",
    type: "service",
    price: 8000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Beaute & Bien-etre",
    categoryId: "cat6",
    seller: users[5],
    location: "Abomey-Calavi",
    rating: 4.8,
    reviewCount: 112,
    views: 1890,
    isPromoted: false,
    isFavorited: false,
    status: "active",
    createdAt: "2025-01-25",
    updatedAt: "2025-02-08",
    tags: ["beaute", "coiffure", "naturel", "soin"],
    deliveryAvailable: false,
    availability: "Mardi - Dimanche, 9h - 19h",
  },
  {
    id: "l6",
    title: "Reparation smartphone - Ecran, batterie, carte mere",
    description: "Reparation professionnelle de smartphones toutes marques (iPhone, Samsung, Huawei, Tecno, Infinix). Ecran, batterie, connecteur de charge, carte mere. Pieces d'origine. Garantie 3 mois.",
    type: "service",
    price: 10000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600"],
    category: "Electronique",
    categoryId: "cat4",
    seller: users[6],
    location: "Cotonou",
    quartier: "Ganhi",
    rating: 4.5,
    reviewCount: 67,
    views: 2100,
    isPromoted: false,
    isFavorited: true,
    status: "active",
    createdAt: "2025-01-18",
    updatedAt: "2025-02-05",
    tags: ["smartphone", "reparation", "ecran", "batterie"],
    deliveryAvailable: false,
    availability: "Lundi - Samedi, 8h30 - 19h",
  },
  {
    id: "l7",
    title: "Lit king size en bois de teck avec tiroirs",
    description: "Lit double king size (200x180cm) en bois de teck massif avec 4 tiroirs de rangement integres. Tete de lit sculptee. Matelas non inclus. Montage gratuit a la livraison.",
    type: "product",
    price: 280000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Menuiserie",
    categoryId: "cat2",
    seller: users[0],
    location: "Cotonou",
    quartier: "Akpakpa",
    rating: 4.9,
    reviewCount: 18,
    views: 980,
    isPromoted: false,
    isFavorited: false,
    status: "active",
    createdAt: "2025-01-28",
    updatedAt: "2025-02-10",
    tags: ["lit", "teck", "rangement", "chambre"],
    deliveryAvailable: true,
    condition: "new",
  },
  {
    id: "l8",
    title: "Poulet braise + accompagnement",
    description: "Delicieux poulet braise assaisonne aux epices locales. Servi avec alloco, attiéké ou riz. Commande minimum 2 portions. Livraison gratuite a partir de 10 000 FCFA.",
    type: "product",
    price: 3000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600"],
    category: "Restauration",
    categoryId: "cat3",
    seller: users[1],
    location: "Porto-Novo",
    quartier: "Ouando",
    rating: 4.9,
    reviewCount: 134,
    views: 4520,
    isPromoted: true,
    isFavorited: false,
    status: "active",
    createdAt: "2025-02-05",
    updatedAt: "2025-02-14",
    tags: ["poulet", "braise", "livraison", "repas"],
    deliveryAvailable: true,
    condition: "new",
  },
  {
    id: "l9",
    title: "Formation WordPress et creation de site web",
    description: "Formation complete pour creer votre site web professionnel avec WordPress. 5 sessions de 3h. Inclus: hebergement 1 an, nom de domaine, formation SEO de base. En presentiel ou en ligne.",
    type: "service",
    price: 75000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Education & Formation",
    categoryId: "cat9",
    seller: users[6],
    location: "Cotonou",
    quartier: "Ganhi",
    rating: 4.7,
    reviewCount: 28,
    views: 760,
    isPromoted: false,
    isFavorited: false,
    status: "active",
    createdAt: "2025-01-12",
    updatedAt: "2025-02-01",
    tags: ["formation", "wordpress", "web", "site"],
    deliveryAvailable: false,
    availability: "Sessions le samedi, 9h - 12h",
  },
  {
    id: "l10",
    title: "Ensemble boubou brode homme",
    description: "Magnifique ensemble boubou pour homme en basin riche brode a la main. Couleurs: blanc, bleu ciel, beige. Tailles: M a XXL. Broderie personnalisable sur commande.",
    type: "product",
    price: 45000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Mode & Vetements",
    categoryId: "cat5",
    seller: users[3],
    location: "Parakou",
    rating: 4.7,
    reviewCount: 56,
    views: 2100,
    isPromoted: false,
    isFavorited: true,
    status: "active",
    createdAt: "2025-02-03",
    updatedAt: "2025-02-12",
    tags: ["boubou", "homme", "basin", "brode"],
    deliveryAvailable: true,
    condition: "new",
  },
  {
    id: "l11",
    title: "Installation et configuration reseau WiFi",
    description: "Installation professionnelle de reseaux WiFi pour maisons et entreprises. Configuration routeur, extension de couverture, securisation. Intervention rapide sous 24h.",
    type: "service",
    price: 20000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600"],
    category: "Electronique",
    categoryId: "cat4",
    seller: users[6],
    location: "Cotonou",
    quartier: "Ganhi",
    rating: 4.4,
    reviewCount: 32,
    views: 670,
    isPromoted: false,
    isFavorited: false,
    status: "active",
    createdAt: "2025-01-22",
    updatedAt: "2025-02-06",
    tags: ["wifi", "reseau", "installation", "internet"],
    deliveryAvailable: false,
    availability: "Lundi - Vendredi, 8h - 17h",
  },
  {
    id: "l12",
    title: "Vidange et entretien complet vehicule",
    description: "Forfait entretien complet: vidange huile moteur, remplacement filtre a huile, filtre a air, verification niveaux, controle freins. Huile de qualite superieure incluse.",
    type: "service",
    price: 25000,
    currency: "FCFA",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "Mecanique",
    categoryId: "cat1",
    seller: users[2],
    location: "Cotonou",
    quartier: "Godomey",
    rating: 4.7,
    reviewCount: 78,
    views: 1340,
    isPromoted: true,
    isFavorited: false,
    status: "active",
    createdAt: "2025-02-08",
    updatedAt: "2025-02-15",
    tags: ["vidange", "entretien", "huile", "auto"],
    deliveryAvailable: false,
    availability: "Lundi - Samedi, 8h - 18h",
  },
]

// --- REVIEWS ---
export const reviews: Review[] = [
  {
    id: "r1",
    userId: "u5",
    userName: "Jean-Baptiste Houessou",
    userAvatar: "/placeholder.svg?height=40&width=40",
    listingId: "l1",
    rating: 5,
    comment: "Table magnifique ! La qualite du bois est exceptionnelle et le travail est tres soigne. Livraison rapide et installation parfaite. Je recommande vivement !",
    createdAt: "2025-02-10",
    sellerResponse: "Merci beaucoup Jean-Baptiste ! Ravi que la table vous plaise. N'hesitez pas a revenir pour d'autres meubles.",
  },
  {
    id: "r2",
    userId: "u10",
    userName: "Grace Hounsa",
    userAvatar: "/placeholder.svg?height=40&width=40",
    listingId: "l4",
    rating: 5,
    comment: "Robe absolument sublime ! Le tissu est de tres bonne qualite et la coupe est parfaite. J'ai recu beaucoup de compliments. Merci Amina !",
    createdAt: "2025-02-12",
  },
  {
    id: "r3",
    userId: "u5",
    userName: "Jean-Baptiste Houessou",
    userAvatar: "/placeholder.svg?height=40&width=40",
    listingId: "l3",
    rating: 4,
    comment: "Bon service, diagnostic rapide et precis. Le prix est correct pour la qualite du travail. Seul bemol: l'attente un peu longue le samedi.",
    createdAt: "2025-02-05",
    sellerResponse: "Merci pour votre retour. Nous travaillons a reduire les temps d'attente le weekend.",
  },
  {
    id: "r4",
    userId: "u10",
    userName: "Grace Hounsa",
    userAvatar: "/placeholder.svg?height=40&width=40",
    listingId: "l2",
    rating: 5,
    comment: "Service traiteur exceptionnel pour mon anniversaire. 80 invites et tout le monde etait ravi. Les plats etaient delicieux et bien presentes. Fati est tres professionnelle.",
    createdAt: "2025-01-30",
  },
  {
    id: "r5",
    userId: "u5",
    userName: "Jean-Baptiste Houessou",
    userAvatar: "/placeholder.svg?height=40&width=40",
    listingId: "l5",
    rating: 5,
    comment: "Mes cheveux n'ont jamais ete aussi beaux ! Les produits naturels sont top. Chantal est tres douce et competente. Je reviens chaque mois.",
    createdAt: "2025-02-08",
  },
  {
    id: "r6",
    userId: "u10",
    userName: "Grace Hounsa",
    userAvatar: "/placeholder.svg?height=40&width=40",
    listingId: "l6",
    rating: 4,
    comment: "Ecran de mon Samsung repare en 2h. Fonctionne comme neuf. Prix raisonnable. Recommande.",
    createdAt: "2025-02-03",
  },
]

// --- ORDERS ---
export const orders: Order[] = [
  {
    id: "ord1",
    buyerId: "u5",
    buyerName: "Jean-Baptiste Houessou",
    sellerId: "u1",
    sellerName: "Akou Mensah",
    items: [{ listing: listings[0], quantity: 1, price: 185000 }],
    total: 185000,
    status: "delivered",
    paymentMethod: "MTN Mobile Money",
    deliveryAddress: "Quartier Gbeto, Cotonou",
    createdAt: "2025-01-20",
    updatedAt: "2025-01-25",
    trackingNumber: "AM-2025-001",
  },
  {
    id: "ord2",
    buyerId: "u10",
    buyerName: "Grace Hounsa",
    sellerId: "u3",
    sellerName: "Amina Bello",
    items: [
      { listing: listings[3], quantity: 2, price: 25000 },
      { listing: listings[9], quantity: 1, price: 45000 },
    ],
    total: 95000,
    status: "shipped",
    paymentMethod: "Moov Money",
    deliveryAddress: "Quartier Tokplegbe, Porto-Novo",
    createdAt: "2025-02-10",
    updatedAt: "2025-02-13",
    trackingNumber: "AM-2025-015",
  },
  {
    id: "ord3",
    buyerId: "u5",
    buyerName: "Jean-Baptiste Houessou",
    sellerId: "u1",
    sellerName: "Akou Mensah",
    items: [{ listing: listings[6], quantity: 1, price: 280000 }],
    total: 280000,
    status: "confirmed",
    paymentMethod: "MTN Mobile Money",
    deliveryAddress: "Quartier Gbeto, Cotonou",
    createdAt: "2025-02-14",
    updatedAt: "2025-02-14",
  },
  {
    id: "ord4",
    buyerId: "u10",
    buyerName: "Grace Hounsa",
    sellerId: "u5",
    sellerName: "Chantal Agossa",
    items: [{ listing: listings[4], quantity: 1, price: 8000 }],
    total: 8000,
    status: "pending",
    paymentMethod: "Especes",
    deliveryAddress: "Sur place - Abomey-Calavi",
    createdAt: "2025-02-15",
    updatedAt: "2025-02-15",
  },
  {
    id: "ord5",
    buyerId: "u5",
    buyerName: "Jean-Baptiste Houessou",
    sellerId: "u2",
    sellerName: "Koffi Dossou",
    items: [{ listing: listings[11], quantity: 1, price: 25000 }],
    total: 25000,
    status: "processing",
    paymentMethod: "MTN Mobile Money",
    deliveryAddress: "Quartier Godomey, Cotonou",
    createdAt: "2025-02-12",
    updatedAt: "2025-02-13",
  },
]

// --- MESSAGES ---
const messagesData: Message[] = [
  {
    id: "m1",
    senderId: "u5",
    receiverId: "u1",
    content: "Bonjour, est-ce que la table en iroko est toujours disponible ?",
    timestamp: "2025-02-14T10:30:00",
    isRead: true,
  },
  {
    id: "m2",
    senderId: "u1",
    receiverId: "u5",
    content: "Bonjour Jean-Baptiste ! Oui, elle est disponible. Vous souhaitez la voir en atelier ?",
    timestamp: "2025-02-14T10:45:00",
    isRead: true,
  },
  {
    id: "m3",
    senderId: "u5",
    receiverId: "u1",
    content: "Oui, je peux passer demain matin. Vous etes a Akpakpa, c'est bien ca ?",
    timestamp: "2025-02-14T11:00:00",
    isRead: true,
  },
  {
    id: "m4",
    senderId: "u1",
    receiverId: "u5",
    content: "Exactement ! Je suis disponible a partir de 9h. Je vous envoie la localisation par WhatsApp.",
    timestamp: "2025-02-14T11:15:00",
    isRead: false,
  },
  {
    id: "m5",
    senderId: "u10",
    receiverId: "u3",
    content: "Bonjour Amina, j'adore la robe Ankara que j'ai commandee ! Est-ce que vous pouvez faire le meme modele en bleu ?",
    timestamp: "2025-02-13T14:20:00",
    isRead: true,
  },
  {
    id: "m6",
    senderId: "u3",
    receiverId: "u10",
    content: "Bonjour Grace ! Merci beaucoup, je suis ravie que ca vous plaise. Oui, j'ai du tissu bleu disponible. Je peux vous l'envoyer en photo ?",
    timestamp: "2025-02-13T14:35:00",
    isRead: true,
  },
  {
    id: "m7",
    senderId: "u10",
    receiverId: "u3",
    content: "Oui s'il vous plait ! Et combien de temps pour la confection ?",
    timestamp: "2025-02-13T14:40:00",
    isRead: false,
  },
]

export const conversations: Conversation[] = [
  {
    id: "conv1",
    participants: [users[4], users[0]],
    lastMessage: messagesData[3],
    unreadCount: 1,
    listingId: "l1",
    listingTitle: "Table a manger en bois massif 6 places",
  },
  {
    id: "conv2",
    participants: [users[9], users[3]],
    lastMessage: messagesData[6],
    unreadCount: 1,
    listingId: "l4",
    listingTitle: "Robe Ankara moderne - Collection 2025",
  },
]

export const messages = messagesData

// --- DELIVERY TASKS ---
export const deliveryTasks: DeliveryTask[] = [
  {
    id: "dt1",
    orderId: "ord2",
    pickupAddress: "Parakou - Boutique Mode Amina",
    deliveryAddress: "Quartier Tokplegbe, Porto-Novo",
    status: "in_transit",
    estimatedTime: "2025-02-16T14:00:00",
    fee: 5000,
    buyerName: "Grace Hounsa",
    sellerName: "Amina Bello",
  },
  {
    id: "dt2",
    orderId: "ord3",
    pickupAddress: "Akpakpa, Cotonou - Atelier Mensah",
    deliveryAddress: "Quartier Gbeto, Cotonou",
    status: "pending",
    estimatedTime: "2025-02-17T10:00:00",
    fee: 3000,
    buyerName: "Jean-Baptiste Houessou",
    sellerName: "Akou Mensah",
  },
]

// --- DASHBOARD STATS ---
export const sellerDashboardStats: DashboardStats = {
  totalSales: 47,
  totalOrders: 52,
  totalListings: 24,
  averageRating: 4.8,
  revenue: 4250000,
  views: 12500,
  conversionRate: 3.8,
  monthlyData: [
    { month: "Sep", sales: 3, revenue: 185000 },
    { month: "Oct", sales: 5, revenue: 320000 },
    { month: "Nov", sales: 7, revenue: 480000 },
    { month: "Dec", sales: 12, revenue: 890000 },
    { month: "Jan", sales: 10, revenue: 750000 },
    { month: "Fev", sales: 10, revenue: 625000 },
  ],
}

export const adminStats: AdminStats = {
  totalUsers: 15420,
  totalListings: 8934,
  totalOrders: 23567,
  totalRevenue: 456000000,
  newUsersToday: 47,
  newListingsToday: 23,
  pendingModeration: 12,
  monthlyData: [
    { month: "Sep", users: 1200, listings: 450, revenue: 32000000 },
    { month: "Oct", users: 1800, listings: 670, revenue: 45000000 },
    { month: "Nov", users: 2100, listings: 780, revenue: 52000000 },
    { month: "Dec", users: 3200, listings: 1100, revenue: 78000000 },
    { month: "Jan", users: 3800, listings: 1340, revenue: 89000000 },
    { month: "Fev", users: 3320, listings: 1200, revenue: 82000000 },
  ],
}

// Helper to format FCFA prices
export function formatPrice(amount: number): string {
  return new Intl.NumberFormat("fr-FR").format(amount) + " FCFA"
}

// Helper to get listing by ID
export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id)
}

// Helper to get user by ID
export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id)
}

// --- NOTIFICATIONS ---
export const notificationsData: import("./types").Notification[] = [
  {
    id: "n1",
    userId: "u1",
    type: "order",
    title: "Nouvelle commande !",
    message: "Jean-Baptiste Houessou a commandé votre Table à manger.",
    isRead: false,
    createdAt: "2025-02-14T10:05:00",
    link: "/dashboard/seller/orders/ord1",
  },
  {
    id: "n2",
    userId: "u1",
    type: "message",
    title: "Nouveau message",
    message: "Vous avez reçu un message de Jean-Baptiste concernant votre annonce.",
    isRead: false,
    createdAt: "2025-02-14T10:30:00",
    link: "/messages",
  },
  {
    id: "n3",
    userId: "u1",
    type: "system",
    title: "Bienvenue sur AfricaMarket Pro",
    message: "Félicitations ! Votre boutique est désormais vérifiée.",
    isRead: true,
    createdAt: "2025-02-01T09:00:00",
  },
  {
    id: "n4",
    userId: "u5",
    type: "promotion",
    title: "Soldes d'été !",
    message: "Profitez de -20% sur la catégorie Mode cette semaine.",
    isRead: false,
    createdAt: "2025-02-15T08:00:00",
    link: "/search?category=mode",
  },
]

// Helper to get reviews for a listing
export function getReviewsForListing(listingId: string): Review[] {
  return reviews.filter((r) => r.listingId === listingId)
}

// Helper to get listings by seller
export function getListingsBySeller(sellerId: string): Listing[] {
  return listings.filter((l) => l.seller.id === sellerId)
}

// Helper to get orders for user
export function getOrdersForUser(userId: string, role: "buyer" | "seller"): Order[] {
  if (role === "buyer") return orders.filter((o) => o.buyerId === userId)
  return orders.filter((o) => o.sellerId === userId)
}
